# Generated by Django 3.1.7 on 2021-04-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210406_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='page2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='page3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='page4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='page5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='page6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
